### ISSUE TITLE
J4 - not searching into database (and fix proposal)

### ISSUE THREAD

**Issue by KlugFR** [JoomTools/tidyup_myfiles#10]
Hello.

We've tried to clean up our /images folder but "nothing happens".

We tried to work on "jpeg" files to restrict the tool, it finds 31 of files.
The URL used is: `/exec.php?all=1&rename=1&ext=jpeg&folder=images&debug=on`

The result is:
`Davon nicht umbenannt, weil schon URL-Safe: 25 Datei/en`
`Der Rest (6 Datei/en) wird, wie folgt, in der Datenbank zur Umbenennung gesucht`
and then:
```
Tidyup my files 0.034 seconds (0.034); 1.07 MB (0.682) - Dateisuche in images


Starte Suche nach Datein in der Datenbank ....

Umbenannte Dateien
Es mussten keine Dateien umbenannt werden.


Bearbeitete Tabellen
Es mussten keine Tabelle bearbeitet werden.
```

It really looks like it's not searching in the database at all.

I'm not a coder but I tried to comment out line 788, 789 and 790.
With the line commented, the script seems to start searching into the database:
```
Starte Suche nach Datein in der Datenbank ....
Durchsuche j3x_action_log_config mit 81 Datensätzen ....................................................................................
Tidyup my files 0.079 seconds (0.026); 1.28 MB (0.110) - Datenbanksuche in j3x_action_log_config und 81 Datensätzen ergab: 
0 Treffer




Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 27279360 bytes) in /joomla_path/libraries/vendor/joomla/database/src/Mysqli/MysqliStatement.php on line 470
``` 

So I went a bit further and added 'action_logs' to the _EXCLUDE_TABLE_ arrays.
Now I'm getting the script to search into the tables, one by one (for 250 tables before it fails again with memory exhaustion).

The interesting part is:
```
Durchsuche j3x_content mit 15021 Datensätzen ...................................................................................
Tidyup my files 17.766 seconds (0.000); 101.99 MB (0.001) - Datenbanksuche in j3x_content und 15021 Datensätzen ergab: 
6 Treffer (Pentecôte.jpeg, L_Europe_à_coeur.jpeg, Réserver.jpeg, Lart_caché_Aude_de_Kerros.jpeg, Les_ÉCO_N_350601.jpeg, Itinéraire.jpeg)
```
So it did found the files in the database and proposed to rename them!

I had to add a couple other tables to the exclusion list (see at the end) to something that seems to work:
```
Umbenannte Dateien
Die Datei images/Itinéraire.jpeg wurde in den Tabellen j3x_content (introtext) gefunden und in images/Itineraire.jpeg umbenannt.
Die Datei images/L_Europe_à_coeur.jpeg wurde in den Tabellen j3x_content (images) j3x_ucm_content (core_images) gefunden und in images/L_Europe_a_coeur.jpeg umbenannt.
Die Datei images/Lart_caché_Aude_de_Kerros.jpeg wurde in den Tabellen j3x_content (images) j3x_ucm_content (core_images) gefunden und in images/Lart_cache_Aude_de_Kerros.jpeg umbenannt.
Die Datei images/Les_ÉCO_N_350601.jpeg wurde in den Tabellen j3x_content (images) j3x_ucm_content (core_images) gefunden und in images/Les_ECO_N_350601.jpeg umbenannt.
Die Datei images/Pentecôte.jpeg wurde in den Tabellen j3x_content (images) j3x_ucm_content (core_images) gefunden und in images/Pentecote.jpeg umbenannt.
Die Datei images/Réserver.jpeg wurde in den Tabellen j3x_content (introtext) gefunden und in images/Reserver.jpeg umbenannt.

Bearbeitete Tabellen
Es wurden 10 SQL-Queries ausgeführt:


Debug Modus aktiv, nix passiert :-)
```

I re-tried the script with "debug=off" and it renames the files on the disk and the record in the database.

In the end, to sum up:
- comment out or fix lines 788, 789, 790
- add 'action_logs' and 'history' and 'redirect_link' to _EXCLUDE_TABLE_

**Comment by degobbis** [comment]
Thank you for bringing this to my attention.

The 3 lines of code you deleted shouldn't have been there at all, they were meant for debugging j2store.
I followed your suggestions to exclude the action logs, as well as the redirects.
However, the history table must remain so that the file with the new name can also be used when restoring a previous version.

So please test the updated branch "joomla4" and report.

**Comment by KlugFR** [comment]
I'm trying the new version.

I have truncated the history table (dev website), so the script is able to go further that this table (or it exhausts memory on this table).

But I had some memory exhaustion anyway, at the end of going through every tables.
I raised the memory_limit and got rid of it.

That was with debug=on.
Running the script with debug=off did not work as expected.

MariaDB spent a lot of time updating j3x_content (I was able to see it with the `show processlist;`command) and this did not end up correctly (PHP timed out before the end of the updates).
It looks like the database is not fully updated and as the script stops, it doesn't renamed the files.

`2024-02-27_15.59.05_datenbank.sql`is huge (6'536'322 bytes) so I guess that's why the process ends up in time out.

So I took the SQL file and executed in though CLI (`mysql database < 2024-02-27_15.59.05_datenbank.sql').
That went well.

But I have to rename the files manually (based on the result of the script with debug=on).
Would it be possible to create a file on the server, just like the SQL file, with the "rename commands" in it (so we can run it though CLI if needed)?

**Comment by degobbis** [comment]
What are the values of max_execution_time and memory_limit?

**Comment by KlugFR** [comment]
Well, it's much worse than this, the SQL file is not correct at all.

I just tried a run (debug on) for "pdf" files.
The scripts ends up correctly with:
```
Bearbeitete Tabellen
Es wurden 7222 SQL-Queries ausgeführt:
```

The SQL file is 21666 lines. It's the same file that the previous tries (the one for "png" files).
The content has nothing to do with just "tidying" one type of files.

Previous tries (on "jpeg") gave correct SQL files (30 lines) that contained only the correct updates.
The according "filesCopied.txt" files had 5 lines in it (no unicode characters).

**Comment by KlugFR** [comment]
Bogus tries were made with default max_execution_time (3600) and 1024M for memory limit (instead of 512M).
600M ends up with memory exhaustion, 700MB works but creates the same huge SQL file.

I've diffed exec.php, there's nothing else than the patch for this issue (removed lines).

There might be something else.

**Comment by KlugFR** [comment]
There are files with (broken) unicode characters.
![filename](https://github.com/joomtools/tidyup_myfiles/assets/6048396/0a375fab-1b1b-4bf8-890b-b4ab6fd26c9e)

Could this be related?

**Comment by degobbis** [comment]
Hm...

The SQL file is only generated when the search in the database has been completed.
This can take longer with many data records.

Because the UPDATE queries via PHP then take too long in any case, I have outsourced this to an SQL file and execute it at shell level, which is much faster.

A new file (date_time_with_seconds) should have been created for script call.

The files are only copied and renamed once this has run without errors.
The broken Unicode charters should not play a significant role in this.
I will consider your suggestion to write the rename/delete process to a file and then execute it in the shell.

But perhaps you could check whether the values for max_execution_time and memory_limit are also used correctly within the script.

Please check by calling `exec.php?phpinfo=1`.

**Comment by KlugFR** [comment]
I checked with phpinfo and the values are correct: 3600s and 700 MB (less leads to exhaustion), much higher than the "master" values.

It's definitively the unicode that is causing issue.

I've moved the PDF file (the one from the screenshot above) out of /images folder then relaunched the script.
I'm getting a 7889 bytes SQL file with 1362 lines in it (instead of the huge file).
If launched without debug mode, the script does it job perfectly (fixes the database and rename the files).

This (removing the files with a unicode char) also fixed the Joomla Media Manager.
It was empty (no files, no folders) and it now shows the

**Comment by degobbis** [comment]
Then I was wrong to assume that the broken Unicode file names were not a problem.
I'll have to see if I can intercept this somehow so that it doesn't lead to these crashes.
Can you possibly share a few such files with me for testing purposes?

As it seems, the problem also exists directly in Joomla and is not so easy to fix.

Can we then close this issue?

**Comment by KlugFR** [comment]
Issue can be closed, thanks for your help.

I'll try to make a tgz with a couple of the files with name issues and upload it.
