### ISSUE TITLE
interface also in English ?

### ISSUE THREAD

**Issue by woluweb** [JoomTools/tidyup_myfiles#8]
Hi,
Txs a lot for this excellent script that I am discovering/testing now :) !

I had only one suggestion : unfortunately (even if I was there at #jd17de) my German is too poor..
Would it possible to provide an English version of the interface ? (I feel indeed a bit stressed not knowing exactly what the script says ;) )

**Comment by degobbis** [comment]
Hi,
thx for the feedback, i want to see what i can do to offer the output in english.

How did you hear about this tool?

**Comment by woluweb** [comment]
I discovered this tool via Elisa. I don't remember how exactly :)
(a post on Facebook or slides of a conference ?)

BTW, 2 extra Tables to excludes (besides the ones I mentionned in my Pull Request) : 
	'imagerecycle_files',
	'imagerecycle_options',

**Comment by woluweb** [comment]
FYI, here are the two other tools that I am aware of allowing to find orphan files:
1.
https://gist.github.com/renekreijveld/27d9062b941a2d0c80f3
https://gist.github.com/renekreijveld/9663741
2.
https://www.r2h.nl/joomla-extensions/imagemanager

**Comment by degobbis** [comment]
There is no PR for your 2 extra tables. 
Please tell me why these tables should be excluded, or what is in it?

I know the scripts from 1. However, I am not sure if they also consider Json parameters or serialized values in the database. In the latter case, you destroy the contents.

I don't know the imagemanager extension.

**Comment by woluweb** [comment]
The tables to be excluded are those of myJoomla (very large tables + they keep track of deleted files).
(For Image Recycle, the table should not be very big, but I had the impression that they contained already deleted images)

	'bf_files',
	'bf_files_last',
	'bf_activitylog',
	'bf_core_hashes',
	'bf_folders',
	'bf_folders_to_scan',
	'imagerecycle_files',
	'imagerecycle_options',

Image Manager is a paid extension, but it allows a simple user to see his/her images, to drag&drop the images (and the link gets adapted of course) etc.

**Comment by degobbis** [comment]
What to consider before I can exclude tables is whether the tables have filenames that are changed by my script. If this is the case, I have to adjust this in the tables, otherwise there will be problems in the operation of the extension.
However, the MyJoomla tables could be snapshots to detect changes on files and fodlers, so it might be better to exclude them.
Could you check that?

**Comment by woluweb** [comment]
OK, I think I understand.

Like if slideshow links to images, if we rename the images we should also rename the filenames in the database. Right ?

So in that case, I can confirm that myJoomla.com makes (weekly/monthly) audits of files.
It does not matter whether there are deleted files/new files/changed files : it will be refreshed during the next audit (as far as I know, but I am not the developer :) )

Also, I don't know how you manage (or not) the Joomla Versions : an image could still be in the content table... bc it was used in one of the previous versions... which may never been purged.
So maybe a switch "keep images/PDF being in old Versions of the Articles" or "do not keep them" would make sense bc it can have a tremendous impact I have noticed...

**Comment by degobbis** [comment]
You recognized it correctly.

It makes no sense to keep the wrong file names in older versions of an article, because if I want to restore an older version, then the image should be loaded in any case (then just with the new name).

There is also the option to delete unused images, again, it makes sense to consider the old article versions.

For the Joomla versions, I expect at least Joomla 3.8, but I do not check it.

Maybe I just misunderstood what you meant :-)

**Comment by woluweb** [comment]
Yep, coming back to "Article versions" : I was indeed too short in my explanation:
- if your script is used to rename then of course you also want to rename there
- but if your script is used to detect Unused files, there an option to Delete (or Not) images which are not present any more in the *current* version of the articles makes sense.
I had the case for a site with thousands of images... but they were all present in old Versions of the articles... and the idea was indeed to delete them (I was surprised that almost all images were "used"... while they were obviously not present on the live site. Then I realized that Joomla Versioning was giving a truncated vision. So giving the choice to Delete an image if it is only present in previous Versions is helpful)

**Comment by degobbis** [comment]
I can understand your argument, but the point is to be able to return to an earlier version without losing the pictures.
If the version is no longer interesting for you, please clean it first ;-)

**Comment by woluweb** [comment]
Sure, *I* can do that bc I am *aware* of that :).
I was only suggesting a potential new feature, like [DeleteIfOnlyInVersioning=1].
Many people would simply not realize that their old unused pictures are still somewhere in the database... in Versioning.
