### ISSUE TITLE
Compatible with J4?

### ISSUE THREAD

**Issue by woluweb** [JoomTools/tidyup_myfiles#9]
Hi Guido,
I discover this nice little script.
Is it compatible with J4 (or only with J3)?
Txs,
Marc

PS: will you be at #jd23dach? I will be there :)

**Comment by degobbis** [comment]
Hi Marc, yes I'm on jd23dach this year.
For J4 support, please test the joomla4 branch https://github.com/joomtools/tidyup_myfiles/tree/joomla4

**Comment by woluweb** [comment]
Oh, I had not seen the branch :)
Txs a lot.
Here is a preview of 1 of my presentations at #jd23dach, mentioning your tool ;)
https://slides.woluweb.be/gems/gems.html#9-8-2-tidyup-myfile
Txs again!

**Comment by degobbis** [comment]
Nice, thx.
I hope it works as expected for Joomla 4.
